# Site settings
title: ab180
header-img: img/home-bg.jpg
email: dl_all@udl.io
description: "Our mission is to collect IN-APP CONTENTS and make it universally accessible and useful."
baseurl: ""
url: "ab180.github.io"
twitter_username:
github_username:  ab180
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
